# SITE CONFIGURATION
baseurl: "/"
url: "https://larel-ws.github.io"

# THEME-SPECIFIC CONFIGURATION
title: LaReL 2020                                    # site's title
description: "Language in Reinforcement Learning Workshop"      # used by search engines
avatar: # assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: # assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: The 1st Language in Reinforcement Learning Workshop 2020 at ICML 2020
footer_text: Copyright 2020

# External links
external:
  # - title: OpenReview
  #   url: https://openreview.net/group?id=ICML.cc/2020/Workshop/LaReL

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: 

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
# collections:
#   portfolio:
#     output: true
#     permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
